[project]
name = "cleaninput-ai-engine"
version = "0.1.0"
entrypoint = "main:predict"

[hardware]
region = "us-east-1"
device = "cpu"
cpu = 2
memory = 4.0

[scaling]
min_replicas = 0
max_replicas = 500
cooldown = 10

